const weatherBackgrounds = {
    '1': '/sunny.jpg',
    '2': '/sunny.jpg',
    '3': '/sunny.jpg',
    '4': '/sunny.jpg',
    '5': '/sunny.jpg',
    '6': '/cloudy.jpg',
    '7': '/cloudy.jpg',
    '8': '/cloudy.jpg',
    '11': '/cloudy.jpg',
    '12': '/rain.jpg',
    '13': '/rain.jpg',
    '14': '/rain.jpg',
    '15': '/rain.jpg',
    '16': '/rain.jpg',
    '17': '/rain.jpg',
    '18': '/rain.jpg',
    '19': '/cloudy.jpg',
    '20': '/cloudy.jpg',
    '21': '/sunny.jpg',
    '22': '/snow.jpg',
    '23': '/snow.jpg',
    '24': '/snow.jpg',
    '25': '/snow.jpg',
    '26': '/rain.jpg',
    '29': '/rain.jpg',
    '32': '/windy.jpg',
    '33': '/moon.jpg',
    '34': '/moon.jpg',
    '35': '/moon.jpg',
    '36': '/moon.jpg',
    '37': '/moon.jpg',
    '38': '/moon.jpg',
    '39': '/rainy night.jpg',
    '40': '/rainy night.jpg',
    '41': '/rainy night.jpg',
    '42': '/rainy night.jpg',
    '43': '/rainy night.jpg',
    '44': '/rainy night.jpg',
};
export default weatherBackgrounds;